[package]
name = "stam"
version = "0.4.0"
edition = "2021"
authors = ["Maarten van Gompel <proycon@anaproy.nl>"]
description = "STAM is a library for dealing with standoff annotations on text"
documentation = "https://docs.rs/stam"
homepage = "https://github.com/annotation/stam"
include = ["src/**/*","tests/**/*", "LICENSE", "README.md"]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/annotation/stam-rust"
keywords = [ "text-processing", "annotation", "linguistics", "standoff", "nlp"]

[dependencies]
chrono = "0.4.23"
sealed = "0.4.0"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
serde_path_to_error = "0.1.11"
smallvec = "1.10.0"
regex = "1"
nanoid = "0.4.0"
csv = "1.2.1"

[features]
default = ["csv"]
csv = []

[dev-dependencies]
criterion = "0.4.0"


[[bench]]
harness = false
path = "benches/benchmarks.rs"
name = "benchmarks"

