name: Rust CI

on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/**'

  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Build Environment
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get install cargo rustc
             fi

      - name: Build and test
        id: test
        run: cargo test
        continue-on-error: true
